tests: do not store environment information
This prevents accidental secret leakage.

Signed-off-by: Nikos Mavrogiannopoulos <n.mavrogiannopoulos@gmail.com>

diff --git a/tests/connect-ios-script b/tests/connect-ios-script
--- a/tests/connect-ios-script
+++ b/tests/connect-ios-script
@@ -2,11 +2,11 @@
 
 #echo $USERNAME : $REASON : $DEVICE
 
-env >apple-ios.$REASON.tmp
+builddir=${builddir:-.}
 
 verify_env_set() {
 	if test -z "${!1}";then
-		echo "Fail: $1 environment variable was not set" >>apple-ios.$REASON.tmp
+		echo "Fail: $1 environment variable was not set" >&2
 		exit 1
 	fi
 }
